export const SAVE_COLLECTION_DETAILS = 'SAVE_COLLECTION_DETAILS'
export const COLLECTION_DETAILS_REQUEST = 'COLLECTION_DETAILS_REQUEST'
export const COLLECTION_DETAILS_FAIL = 'COLLECTION_DETAILS_FAIL'

export const SAVE_ITEM_DETAILS = 'SAVE_ITEM_DETAILS'
